//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FK_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileKeeper_View_1
    {
        public string File_Name { get; set; }
        public string File_Number { get; set; }
        public string File_Room { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string User_Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> User_ID { get; set; }
        public int File_ID { get; set; }
        public string User_Type { get; set; }
        public Nullable<bool> Availability { get; set; } = true;
    }
}
