//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FK_Application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FK_DbEntities4 : DbContext
    {
        public FK_DbEntities4()
            : base("name=FK_DbEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Files_tbl> Files_tbl { get; set; }
        public virtual DbSet<Login_tbl> Login_tbl { get; set; }
        public virtual DbSet<FileKeeper_View_1> FileKeeper_View_1 { get; set; }
    }
}
